baseURL = "https://juni2dev.github.io/ed-blog/"
languageCode = "fr"
title = "Edmond Kameni | Blog"
theme = "PaperMod"

[params]
  author = "Edmond Kameni"
  description = "Cybersécurité, Réseaux, ML & DevOps"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Portfolio"
    url = "https://juni2dev.github.io"
    weight = 2
